Class Note + NoteBook
ihahalev/wizard-assistant-bot pull request #4
Opened 2024-05-21 18:41 UTC by ArtemMokhonko

2024-05-21 19:33 UTC, vorotech requested changes

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +        self.data = UserDict()
це здається не потрібно
це NoteBook наслідує UserDict, а data це вже dict

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +    def search_tag(self):
мене збиває назва цього метода і `searchstring` (доречі немає однаковості в назвах - теж не дуже) 
я очікував що метод щосб шукає:, а тут повертається рядок
назва метода має бути щось типа `get_tags_string` а вище `get_search_string`

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +        self.data[note.title] = note
якщо title такий самий, то перезапише попередню нотатку
на мою думку ключ має бути дата створення а не title

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +        self.data[args[0]].content = (' '.join(args[1:]))
взагалі не розумію що тут відбувається
чому не зробити параметри функції явні? або хоча б коментарі

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +        self.data.pop(args[0])
так само як и попередній

2024-05-21 19:33 UTC, vorotech commented on classes/Note_class.py
> +print(note)
все що ми тестуємо таким чином має бути винесено в тести

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +        self.data = UserDict()
Дякую все переробив

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +    def search_tag(self):
Дякую все переробив

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +        self.data[note.title] = note
Дякую все переробив

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +        self.data[args[0]].content = (' '.join(args[1:]))
Дякую все переробив

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +        self.data.pop(args[0])
Дякую все переробив

2024-05-22 12:34 UTC, ArtemMokhonko commented on classes/Note_class.py
> +print(note)
Дякую все переробив

2024-05-22 15:28 UTC, ihahalev commented on src/remembrall/classes/Note_class.py
> +            raise NameError
гадаю тут інший вийняток
```suggestion
            raise NoteError
```

2024-05-22 20:11 UTC, ihahalev commented on src/remembrall/classes/Note_class.py
> +            raise NoteError
```suggestion
            raise NoteError("No tag to remove")
```

2024-05-23 07:24 UTC, vorotech commented on src/remembrall/classes/Note_class.py
> +    def find_with_context(self, search_str: str) -> list[Note]:
Possible typo? `context` or `content`?

2024-05-23 07:25 UTC, vorotech submitted a review, later dismissed
LGTM

2024-05-23 09:23 UTC, ArtemMokhonko commented on src/remembrall/classes/Note_class.py
> +    def find_with_context(self, search_str: str) -> list[Note]:
виправив, дякую

2024-05-23 09:33 UTC, ihahalev approved these changes

2024-05-23 09:34 UTC, merged